### PR TITLE
repair compile errors and data fetch, fixes #5 and #7

### LINKED ISSUE #5: does not compile in arduino IDE 2.1.0
```
/Users/tlossen/Documents/Arduino/libraries/T9602/src/T9602.cpp: In member function 'uint8_t T9602::begin(uint8_t)':
/Users/tlossen/Documents/Arduino/libraries/T9602/src/T9602.cpp:12:1: error: no return statement in function returning non-void [-Werror=return-type]
   12 | }
      | ^
/Users/tlossen/Documents/Arduino/libraries/T9602/src/T9602.cpp: In member function 'bool T9602::sleep()':
/Users/tlossen/Documents/Arduino/libraries/T9602/src/T9602.cpp:74:1: error: no return statement in function returning non-void [-Werror=return-type]
   74 | }
      | ^
cc1plus: some warnings being treated as errors

exit status 1

Compilation error: exit status 1
```

### PR DESCRIPTION
**Pull request by tlossen**
with these trivial changes, it compiles for me. maybe arduino 2.1.0 is more strict, treating more compiler warnings as errors?

### CODE REVIEW

**Comment by tlossen** [comment]
temperature output looks ok now:

```
09:29:52.222 -> 55.04,21.72,
09:29:53.224 -> 55.09,21.72,
09:29:54.239 -> 55.19,21.72,
```

**Comment by awickert** [comment]
Thank you, quite belatedy, for the fix. I had not realized that this would be a problem.
I have indeed only used this with Arduino <2.
And the streamlining is much appreciated as well! @bschulz1701, in case you haven't seen this, tagging you too.

**Comment by awickert** [comment]
I am not able to test with what I have here, but considering that this has worked for @tlossen and this is not exactly an always-used repo, I'm going to merge this in and be a bit more aware if complaints arise.
