### ISSUE TITLE
does not compile in arduino IDE 2.1.0

### ISSUE THREAD

**Issue by tlossen** [NorthernWidget-Skunkworks/T9602_Library#5]
```
/Users/tlossen/Documents/Arduino/libraries/T9602/src/T9602.cpp: In member function 'uint8_t T9602::begin(uint8_t)':
/Users/tlossen/Documents/Arduino/libraries/T9602/src/T9602.cpp:12:1: error: no return statement in function returning non-void [-Werror=return-type]
   12 | }
      | ^
/Users/tlossen/Documents/Arduino/libraries/T9602/src/T9602.cpp: In member function 'bool T9602::sleep()':
/Users/tlossen/Documents/Arduino/libraries/T9602/src/T9602.cpp:74:1: error: no return statement in function returning non-void [-Werror=return-type]
   74 | }
      | ^
cc1plus: some warnings being treated as errors

exit status 1

Compilation error: exit status 1
```
